---

- name: Ensure the sshuttle install directory exists
  file:
    path: "{{ sshuttle_install_dir }}"
    state: directory

- name: Ensure the azure-cli bin directory exists
  file:
    path: "{{ sshuttle_bin_dir }}"
    state: directory
  when: sshuttle_install_venv_helper is defined
        and sshuttle_install_venv_helper

- name: Ensure Python 3 interpreter is used by Ansible
  set_fact:
    ansible_python_interpreter: "{{ sshuttle_python3_path }}"

- name: Ensure sshuttle is installed in a virtual environment
  pip:
    name: sshuttle
    version: "{{ sshuttle_version }}"
    state: present
    virtualenv: "{{ sshuttle_install_dir }}/sshuttle-{{ sshuttle_version }}"
    virtualenv_command: "{{ sshuttle_python3_path }} -m venv"

- name: Ensure the originally configured Python interpreter is used by Ansible
  set_fact:
    ansible_python_interpreter: "{{ sshuttle_ansible_python_interpreter }}"
  when: sshuttle_ansible_python_interpreter is defined

- name: Ensure the current release is symlinked in the install directory
  file:
    src: "{{ sshuttle_install_dir }}/sshuttle-{{ sshuttle_version }}"
    dest: "{{ sshuttle_install_dir }}/{{ sshuttle_current_dirname }}"
    state: link

- name: Ensure venv wrapper exists in virtualenv bin directory
  template:
    src: venv.sh.j2
    dest: "{{ sshuttle_install_dir }}/sshuttle-{{ sshuttle_version }}/bin/venv"
    mode: 0755
  loop:
    - python

- name: Ensure venv helper exists for az in bin directory
  template:
    src: venv.sh.j2
    dest: "{{ sshuttle_bin_dir }}/{{ item }}"
    mode: 0755
  loop:
    - sshuttle
  when: sshuttle_install_venv_helper is defined
        and sshuttle_install_venv_helper
