---

- name: Check the path for Python
  command: which python3
  register: sshuttle_check_python_3_path
  failed_when: sshuttle_check_python_3_path.rc > 0
  changed_when: false
  when: sshuttle_python3_path is not defined

- name: Ensure the path to Python 3 is set as a fact
  set_fact:
    sshuttle_python3_path: "{{ sshuttle_check_python_3_path.stdout }}"
    sshuttle_ansible_python_interpreter: "{{ ansible_python_interpreter | default(omit) }}"
  when: sshuttle_python3_path is not defined
