---
- name: Converge
  hosts: all
  become: true
  vars:
    sshuttle_install_os_dependencies: true
    sshuttle_install_dir: /opt/sshuttle/bin
    sshuttle_bin_dir: /usr/bin
    sshuttle_venv_name: current
  roles:
    - role: xanmanning.sshuttle
